name: Build and Pack

on:
  push:
    branches: [ "main", "releases/*" ]
  pull_request:
    branches: [ "main", "releases/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build

    - name: Check for Release Branch
      id: check_release
      shell: bash
      run: |
        VERSION="0.0.1-preview"
        REF_NAME="${{ github.ref_name }}"

        # Check for refs/heads/releases/X.Y.Z or X.Y.Z-suffix
        if [[ "$REF_NAME" =~ ^releases/([0-9]+\.[0-9]+\.[0-9]+(-.*)?)$ ]]; then
          VERSION=${BASH_REMATCH[1]}
          echo "is_valid_release=true" >> $GITHUB_OUTPUT
        fi

        echo "Extracted Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Pack
      working-directory: ./Cel.Compiled
      run: dotnet pack -c Release --no-build -p:PackageVersion=${{ steps.check_release.outputs.version }} -p:Version=${{ steps.check_release.outputs.version }}

    - name: Upload NuGet Package
      if: steps.check_release.outputs.is_valid_release == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: Cel.Compiled/bin/Release/*.nupkg

    - name: Publish to NuGet
      if: steps.check_release.outputs.is_valid_release == 'true'
      run: dotnet nuget push Cel.Compiled/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
